### ISSUE TITLE
Why does ec-cli use ~/.cache/ec/images/ for storage instead of ~/.local/share/containers/storage ?

### ISSUE THREAD

**Issue by ralphbean** [enterprise-contract/ec-cli#1813]
I don't know if I'd call this a bug, but.. when I'm dealing with huge images locally, I will validate them with ec and also pull them. I end up pulling them twice and storing them twice, once in `~/.cache/ec/images/`  and another time in `~/.local/share/containers/storage`

Could ec be modified to use the same container storage as other tools to de-duplicate?

**Comment by zregvart** [comment]
We'd have to implement support for OCI local storage in go-containerregistry, or stop depending on go-containerregistry -- which might be more difficult to do as cosign depends on it.

**Comment by zregvart** [comment]
I'm actually not sure if local storage is defined by an OCI specification or a https://github.com/containers/ thing, we might leverage https://github.com/containers/storage for the implementation. Might help with #1109.

**Comment by lcarva** [comment]
> Why does ec-cli use ~/.cache/ec/images/ for storage instead of ~/.local/share/containers/storage ? 

I believe this is answered above. It's because EC uses [go-containerregistry](https://github.com/google/go-containerregistry) instead of the [containers](https://github.com/containers) set of libraries. EC "inherits" go-containerregistry via cosign.

> I'm dealing with huge images locally, I will validate them with ec and also pull them. I end up pulling them twice and storing them twice
> Could ec be modified to use the same container storage as other tools to de-duplicate?

This should no longer be the case for these large images since https://github.com/enterprise-contract/ec-cli/pull/1986. The only images that the EC CLI will download are operator bundles, but those are usually tiny.

It is however also possible to download images directly from rego via [ec.oci.image_files](https://enterprisecontract.dev/docs/ec-cli/main/ec_oci_image_files.html). That goes through the same code path. But, hopefully, with EC-533 it will be possible to exclude such policy rules as needed.

Something to consider as well is if you're using docker instead of podman, then caching at `~/.local/share/containers/storage` will not help. In fact, the storage layout is just completely different.

Given that A) large images should not be downloaded automatically by EC anymore, and B) the amount of effort required to switch from the go-containerregistry to the containers libraries, and C) there isn't any one single location that would satisfy podman and docker users, and D) cache locations have widely different formats, let's not work towards making this change.

I'm gonna go ahead and close this out. Please, feel free to re-open if you think your question was not addressed properly. Thanks!
